config/routes.rb
Rails.application.routes.draw do

  get 'orders/index'

  get 'orders/new'

  post 'orders' => 'orders#create'
  
  resources :food_items
  get 'menu' => 'home#menu'

  get 'contact_us' => 'home#contact_us'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  def image_url_or_default
    if image_url.present?
      image_url
    else
     "http://loremflickr.com/320/240/#{name.gsub(' ', '+')}"
    end
  end

  def self.search(search)
    where("name ILIKE ?", "%#{search}%")
  end

  def self.order_or_default(column, direction)
    order(column.present? ? "#{column} #{direction}" : "name asc")
  end
end

app/models/section.rb
class Section < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :image_url, :section_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def menu
    @sections = Section.all
    if params[:section].present?
      @food_items = FoodItem.where(section_id: params[:section].to_i)
    elsif params[:search].present?
      @food_items = FoodItem.search(params[:search])
    else
      @food_items = FoodItem.all
    end
    @food_items = @food_items.order_or_default(params[:sort_column], params[:sort_direction])
  end

  def contact_us
  end

  private 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
    @food_item = FoodItem.find(params[:food])
  end

  def create
    @order = params.permit([:food, :name, :phone, :address])
    @food_item = FoodItem.find(params[:food])
    @delivery = 20000
    @total = @food_item.price + @delivery
    @order_time = Time.now.strftime("%A, %B %d %Y, %H:%M")
    render :thanks
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar
    content_tag(:ul, class: "navbar-nav mr-auto") do
      yield
    end
  end

  def nav_link(text, path)
    options = current_page?(path) ? { class: "nav-item active" } : {class: "nav-item"}
    content_tag(:li, options) do
      link_to text, path, class: "nav-link"
    end
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def nav_section(class_option)
    content_tag(:ul, class: class_option) do
      yield
    end
  end

  def section_link(section)
    active_class = "active" if params[:section].to_i === section.id
    content_tag(:li, { class: "nav-item" }) do
      link_to section.name, menu_path(section: section.id), class: "nav-link #{active_class}"
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :food_item_image_url %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.select :section_id, Section.all.map{|s| [s.name, s.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image url</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= image_tag food_item.image_url_or_default, style: 'max-width: 200px' %></td>
        <td><%= food_item.section.name %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<div class="card">
  <%= image_tag @food_item.image_url_or_default, class: "card-img-top", alt: "#{@food_item.name}" %>
  <div class="card-block">
    <h5 class="card-title"><%= @food_item.name %></h5>
    <div class="card-text">
      <%= @food_item.description %>
    </div>
  </div>
  <div class="card-footer">
      <div class="row">
        <div class="col-md-8"><span class="badge badge-pill badge-danger"><%= @food_item.price %> VND</span> <small class="badge badge-info"><%= @food_item.section.name %></small></div>
        <div class="col-md-4 text-right">
        <%= link_to(orders_new_path(food: @food_item.id)) do %>
          <button class="btn btn-sm btn-primary">Order</button></div>
        <% end %>
      </div>
    </div>
</div>
<%= link_to 'Back', menu_path %>

app/views/home/contact_us.html.erb
<div class="row">
  <div class="col-md-5">
    <address>
      <strong> Coder Restaurant </strong><br/>
      44 Hoa Hong St., Phu Nhuan Dist., Ho Chi Minh City <br/>
      Phone: +84 91 529 88 19
    </address>
  </div>
  <div class="col-md-7">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.192230396075!2d106.68863071448591!3d10.796584361774336!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528ce42af10b7%3A0x277f815609f1ef88!2sTrung+Nguyen+Coffee!5e0!3m2!1sen!2s!4v1497771500298" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/home/menu.html.erb
<h1>Menu</h1>
<%= nav_section("nav nav-pills") do %>
  <% @sections.each do |section| %>
    <%= section_link section %>
  <% end %>
<% end %>
<br>
<div class="card">
  <%= form_tag nil, method: 'get', class: 'card-block form-inline' do %>
    <div class="form-group">
      <%= hidden_field_tag :section, params[:section] %>
      <%= select_tag :sort_column, options_for_select(['name', 'price'], params[:sort_column]), class: 'form-control' %>
      <%= select_tag :sort_direction, options_for_select(['asc', 'desc'], params[:sort_direction]), class: 'form-control' %>
      <%= submit_tag 'Sort', class: 'btn btn-secondary'%>
    </div>
  <% end %>
</div>
<% @food_items.each do |item| %>
  <div class="card" style="width: 320px">
    <%= link_to(item) do %>
      <%= image_tag item.image_url_or_default, class: "card-img-top", alt: "#{item.name}" %>
    <% end %>
    <div class="card-block">
      <h5 class="card-title"><%= item.name %></h5>
    </div>
    <div class="card-footer">
      <div class="row">
        <div class="col-md-8">
          <span class="badge badge-pill badge-danger"><%= item.price %> VND</span> <small class="badge badge-info"><%= item.section.name %></small>
        </div>
        <div class="col-md-4">
          <%= link_to(orders_new_path(food: item.id)) do %>
            <button class="btn btn-sm btn-primary">Order</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-faded" style="background-color: #d9534f; margin-bottom: 20px">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Coder Restaurant</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= nav_bar do %>
      <%= nav_link 'Menu', menu_path %>
      <%= nav_link 'Contact Us', contact_us_path %>
    <% end %>
    <%= form_tag menu_path, method: 'get', class: 'form-inline my-2 my-lg-0' do %>
      <%= text_field_tag :search, params[:search], class: 'form-control mr-sm-2', placeholder: 'Search'%>
      <%= submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0'%>
    </form>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoderRestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="card">
  <%= image_tag food_item.image_url_or_default, class: "card-img-top", alt: "#{food_item.name}" %>
  <div class="card-block">
    <h5 class="card-title"><%= food_item.name %></h5>
    <div class="card-text">
      <%= food_item.description %>
    </div>
  </div>
</div>
<div class="card">
  <%= form_tag orders_path, method: 'post', class: 'card-block' do %>
    <%= hidden_field_tag :food, food_item.id %>
    <div class="form-group">
      <%= label_tag 'name' %>
      <%= text_field_tag 'name', nil, class: 'form-control' %>    
    </div>
    <div class="form-group">
      <%= label_tag 'phone' %>
      <%= text_field_tag 'phone', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= label_tag 'address' %>
      <%= text_area_tag 'address', nil, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= submit_tag 'Submit', class: 'btn btn-primary'%>
    </div> 
  <% end %>
</div>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>New Order for <strong><%= @food_item.name %></strong></h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', menu_path %>

app/views/orders/thanks.html.erb
<h1>Thank you for your order page</h1>

<p>
  <strong>Item name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Delivery:</strong>
  <%= @delivery %>
</p>

<p>
  <strong>Total:</strong>
  <%= @total %> VND
</p>

<p>
  <strong>User name:</strong>
  <%= @order[:name] %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order[:phone] %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order[:address] %>
</p>

<p>
  <strong>Order time:</strong>
  <%= @order_time %>
</p>

<%= link_to 'Back', menu_path %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-3">Coder Restaurant</h1>
  <p class="lead">Welcome to the restaurant for coder.</p>
</div>